name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - packages/container/**

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      # setup AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/aws-cli@v2 
        with:
          aws-region: ap-southeast-1 

      # deploy the website to Amazon S3
      - name: Deploy website to Amazon S3
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME}}/container/latest --delete 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1
